apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8080"
spec:
  selector:
    app: jenkins-server
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: jnlp
      port: 50000
      targetPort: jnlp
